### ISSUE TITLE
FSM graph video is unavailable

### ISSUE THREAD

**Issue by digvijay01** [flipkart-incubator/flux#66]
The video on how Flux state machine graphs look like is unaviable.

The link is in README.md:
Visit https://www.youtube.com/watch?v=DxyNcntnVzQ&feature=youtu.be to see how Flux state machine instance graph and audit look like.

**Comment by shyamakirala** [comment]
Thanks for noticing. Have changed the link, please check https://drive.google.com/file/d/0BxBoQMKaBB04NzRYQXRXdThrNXM/view
